import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ru: {
    'nav.forums': 'Форумы',
    'nav.whatsNew': 'Что нового',
    'nav.members': 'Пользователи',
    'auth.login': 'Вход',
    'auth.register': 'Регистрация',
    'auth.logout': 'Выйти',
    'auth.welcome': 'С возвращением',
    'auth.createAccount': 'Создать аккаунт',
    'auth.username': 'Имя пользователя',
    'auth.email': 'Эл. почта',
    'auth.password': 'Пароль',
    'auth.placeholder.username': 'Введите имя пользователя',
    'auth.placeholder.email': 'name@example.com',
    'auth.placeholder.password': '••••••••',
    'auth.alreadyHave': 'Уже есть аккаунт?',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.error.required': 'Все поля обязательны',
    'sidebar.latestMessages': 'Последние сообщения',
    'sidebar.stats': 'Статистика форума',
    'sidebar.topUsers': 'Топ пользователей',
    'sidebar.threads': 'Темы',
    'sidebar.messages': 'Сообщения',
    'sidebar.members': 'Пользователи',
    'forum.threads': 'Темы',
    'forum.messages': 'Сообщения',
    'forum.subforums': 'Подразделы',
    'forum.noPosts': 'Нет сообщений',
    'forum.lastPost': 'Посл.',
    'forum.by': 'от',
    'forum.ago': 'назад',
    'forum.startedBy': 'Автор',
    'forum.replies': 'Ответов',
    'forum.empty': 'В этом разделе пока нет тем.',
    'thread.locked': 'Закрыто',
    'thread.lockedMsg': 'Эта тема закрыта. Вы не можете отвечать.',
    'thread.share': 'Поделиться',
    'thread.postReply': 'Ответить',
    'thread.loginToReply': 'Войдите, чтобы ответить',
    'thread.writeReply': 'Напишите ответ...',
    'thread.create': 'Создать тему',
    'thread.modalTitle': 'Создать новую тему',
    'thread.formTitle': 'Заголовок темы',
    'thread.formContent': 'Содержание (BBCode поддерживается)',
    'thread.submit': 'Создать тему',
    'thread.prefix': 'Префикс',
    'activity.title': 'Лента активности',
    'activity.subtitle': 'Последние созданные темы и обсуждения на проекте',
    'activity.postedIn': 'в разделе',
    'activity.empty': 'Активности пока нет.',
    'user.messages': 'Сообщения',
    'user.reactions': 'Реакции',
    'user.points': 'Баллы',
    'user.member': 'Участник',
    'user.about': 'О пользователе',
    'user.joined': 'Регистрация',
    'user.rank': 'Ранг',
    'user.signature': 'Подпись',
    'user.recentPosts': 'Недавняя активность',
    'user.noPosts': 'Пользователь еще ничего не публиковал.',
    'user.online': 'В сети',
    'user.bannedStatus': 'ЗАБАНЕН',
    'user.ban': 'Забанить',
    'user.unban': 'Разбанить',
    'general.search': 'Поиск',
    'general.searchPlaceholder': 'Поиск по форуму...',
    'general.searchResults': 'Результаты поиска',
    'general.noResults': 'Ничего не найдено',
    'general.copyCode': 'Копировать код',
    'general.quote': 'Цитата',
    'general.like': 'Нравится',
    'general.likes': 'людям нравится',
    'settings.title': 'Настройки аккаунта',
    'settings.avatar': 'Аватар',
    'settings.banner': 'Баннер',
    'settings.signature': 'Подпись',
    'settings.save': 'Сохранить изменения',
    'settings.success': 'Настройки сохранены',
    'settings.noPermissionAvatar': 'Нет прав на смену аватара',
    'settings.noPermissionBanner': 'Нет прав на смену баннера',
    'settings.signatureHelp': 'Поддерживается: [b], [i], [img], [color]...',
    'settings.newPassword': 'Новый пароль (необязательно)',
    'settings.leaveBlank': 'Оставьте пустым, чтобы не менять',
    'settings.permissions': 'Разрешения',
    
    // Admin Panel Translations
    'admin.title': 'Панель управления',
    'admin.dashboard': 'Дашборд',
    'admin.users': 'Пользователи',
    'admin.forums': 'Форумы',
    'admin.prefixes': 'Префиксы',
    'admin.roles': 'Роли',
    'admin.createCat': 'Создать категорию',
    'admin.createForum': 'Создать форум',
    'admin.createPrefix': 'Создать префикс',
    'admin.createRole': 'Создать роль',
    'admin.edit': 'Изменить',
    'admin.delete': 'Удалить',
    'admin.confirmDelete': 'Удалить? Это действие необратимо.',
    'admin.user': 'Пользователь',
    'admin.email': 'Email',
    'admin.primaryRole': 'Осн. роль',
    'admin.secRole': 'Доп. роль',
    'admin.status': 'Статус',
    'admin.actions': 'Действия',
    'admin.active': 'Активен',
    'admin.banned': 'Забанен',
    'admin.ban': 'Бан',
    'admin.unban': 'Разбан',
    'admin.preview': 'Предпросмотр',
    'admin.catTitle': 'Название категории',
    'admin.forumName': 'Название форума',
    'admin.forumDesc': 'Описание',
    'admin.parentType': 'Тип родителя',
    'admin.selectParent': 'Выберите родителя',
    'admin.insideCat': 'В категории',
    'admin.insideForum': 'В форуме',
    'admin.roleName': 'Название роли',
    'admin.baseColor': 'Цвет',
    'admin.visualEffect': 'Эффект',
    'admin.permissions': 'Права доступа',
    'admin.prefixText': 'Текст префикса',
    'admin.prefixColor': 'Цвет префикса',
    'admin.existingPrefixes': 'Существующие префиксы',
    'admin.existingRoles': 'Существующие роли',
    
    // Colors
    'color.blue': 'Синий',
    'color.green': 'Зеленый',
    'color.red': 'Красный',
    'color.orange': 'Оранжевый',
    'color.yellow': 'Желтый',
    'color.cyan': 'Голубой',
    'color.purple': 'Фиолетовый',
    'color.gray': 'Серый',

    'footer.terms': 'Правила',
    'footer.privacy': 'Конфиденциальность',
    'footer.help': 'Помощь',
    'footer.home': 'Главная',
    'footer.copyright': '© 2023 Black Project Role Play. Платформа сообщества.'
  },
  en: {
    'nav.forums': 'Forums',
    'nav.whatsNew': "What's New",
    'nav.members': 'Members',
    'auth.login': 'Log In',
    'auth.register': 'Register',
    'auth.logout': 'Log Out',
    'auth.welcome': 'Welcome Back',
    'auth.createAccount': 'Create Account',
    'auth.username': 'Username',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.placeholder.username': 'Enter your username',
    'auth.placeholder.email': 'name@example.com',
    'auth.placeholder.password': '••••••••',
    'auth.alreadyHave': 'Already have an account?',
    'auth.noAccount': 'No account yet?',
    'auth.error.required': 'All fields are required',
    'sidebar.latestMessages': 'Latest Messages',
    'sidebar.stats': 'Forum Statistics',
    'sidebar.topUsers': 'Top Users',
    'sidebar.threads': 'Threads',
    'sidebar.messages': 'Messages',
    'sidebar.members': 'Members',
    'forum.threads': 'Threads',
    'forum.messages': 'Messages',
    'forum.subforums': 'Sub-forums',
    'forum.noPosts': 'No posts yet',
    'forum.lastPost': 'Last',
    'forum.by': 'by',
    'forum.ago': 'ago',
    'forum.startedBy': 'Started by',
    'forum.replies': 'Replies',
    'forum.empty': 'No threads in this forum yet. Be the first to post!',
    'thread.locked': 'Locked',
    'thread.lockedMsg': 'This thread is locked. You cannot post new replies.',
    'thread.share': 'Share',
    'thread.postReply': 'Post Reply',
    'thread.loginToReply': 'You must be logged in to reply to this thread.',
    'thread.writeReply': 'Write your reply here...',
    'thread.create': 'Post Thread',
    'thread.modalTitle': 'Create New Thread',
    'thread.formTitle': 'Thread Title',
    'thread.formContent': 'Content (BBCode supported)',
    'thread.submit': 'Post Thread',
    'thread.prefix': 'Prefix',
    'activity.title': 'Activity Stream',
    'activity.subtitle': 'Recently created threads and discussions across the project',
    'activity.postedIn': 'in forum',
    'activity.empty': 'No activity yet.',
    'user.messages': 'Messages',
    'user.reactions': 'Reactions',
    'user.points': 'Points',
    'user.member': 'Member',
    'user.about': 'About',
    'user.joined': 'Joined',
    'user.rank': 'Rank',
    'user.signature': 'Signature',
    'user.recentPosts': 'Recent Posts',
    'user.noPosts': 'User has not posted anything yet.',
    'user.online': 'Online',
    'user.bannedStatus': 'BANNED',
    'user.ban': 'Ban User',
    'user.unban': 'Unban User',
    'general.search': 'Search',
    'general.searchPlaceholder': 'Search forum...',
    'general.searchResults': 'Search Results',
    'general.noResults': 'No results found',
    'general.copyCode': 'Copy Code',
    'general.quote': 'Quote',
    'general.like': 'Like',
    'general.likes': 'people like this',
    'settings.title': 'Account Settings',
    'settings.avatar': 'Avatar (URL)',
    'settings.banner': 'Banner (URL)',
    'settings.signature': 'Signature',
    'settings.save': 'Save Changes',
    'settings.success': 'Settings saved',
    'settings.noPermissionAvatar': 'No permission to change avatar',
    'settings.noPermissionBanner': 'No permission to change banner',
    'settings.signatureHelp': 'Supported: [b], [i], [img], [color]...',
    'settings.newPassword': 'New Password (Optional)',
    'settings.leaveBlank': 'Leave blank to keep current',
    'settings.permissions': 'Permissions',
    
    // Admin Panel
    'admin.title': 'Admin Panel',
    'admin.dashboard': 'Dashboard',
    'admin.users': 'User Management',
    'admin.forums': 'Forums',
    'admin.prefixes': 'Prefixes',
    'admin.roles': 'Roles',
    'admin.createCat': 'Create Category',
    'admin.createForum': 'Create Forum',
    'admin.createPrefix': 'Create Prefix',
    'admin.createRole': 'Create Role',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.confirmDelete': 'Delete? This action cannot be undone.',
    'admin.user': 'User',
    'admin.email': 'Email',
    'admin.primaryRole': 'Primary Role',
    'admin.secRole': 'Secondary Role',
    'admin.status': 'Status',
    'admin.actions': 'Actions',
    'admin.active': 'Active',
    'admin.banned': 'Banned',
    'admin.ban': 'Ban',
    'admin.unban': 'Unban',
    'admin.preview': 'Preview',
    'admin.catTitle': 'Category Title',
    'admin.forumName': 'Forum Name',
    'admin.forumDesc': 'Description',
    'admin.parentType': 'Parent Type',
    'admin.selectParent': 'Select Parent',
    'admin.insideCat': 'Inside Category',
    'admin.insideForum': 'Inside Forum',
    'admin.roleName': 'Role Name',
    'admin.baseColor': 'Base Color',
    'admin.visualEffect': 'Visual Effect',
    'admin.permissions': 'Permissions',
    'admin.prefixText': 'Prefix Text',
    'admin.prefixColor': 'Prefix Color',
    'admin.existingPrefixes': 'Existing Prefixes',
    'admin.existingRoles': 'Existing Roles',
    
    // Colors
    'color.blue': 'Blue',
    'color.green': 'Green',
    'color.red': 'Red',
    'color.orange': 'Orange',
    'color.yellow': 'Yellow',
    'color.cyan': 'Cyan',
    'color.purple': 'Purple',
    'color.gray': 'Gray',

    'footer.terms': 'Terms',
    'footer.privacy': 'Privacy',
    'footer.help': 'Help',
    'footer.home': 'Home',
    'footer.copyright': '© 2023 Black Project Role Play. Community platform.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};